name: Run Crawler - Update data # workflow 이름

on:
  schedule:
    - cron: '*/5 * * * *'
    
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Crawler with python
      run: |
        python "crawler.py"
    - name: Commits
      run: |
        git config --local user.email "king199777@gmail.com"
        git config --local user.name "Update" # 커밋에 포함될 이름
        git add news.json
        git commit -m "Auto - Update data with Crawling" # 커밋 메세지
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'main'
        repo_token: "${{ secrets.CHERRYPICK_IT_TOKEN }}"
